### ISSUE TITLE
Corresponding labels (cancer types) associated with pancan_rnaseq_freeze.tsv.gz

### ISSUE THREAD

**Issue by rezacsedu** [greenelab/pancancer#102]
Hi there,

Thanks for making the code open source. I was also wondering if there corresponding labels (cancer types) associated with pancan_rnaseq_freeze.tsv.gz samples? 

Best,
Karim

**Comment by gwaybio** [comment]
Hi Karim,

Here they are: https://github.com/greenelab/pancancer/blob/master/data/sample_freeze.tsv

**Comment by rezacsedu** [comment]
Hi Greg,

Thanks for the prompt reply, really appreciating! Does the 'DISEASE' column in the sample_freeze.tsv file signify labels, i.e., cancer types?

**Comment by gwaybio** [comment]
yes https://github.com/greenelab/pancancer/blob/master/data/tcga_dictionary.tsv
