### ISSUE TITLE
Cancer type prediction

### ISSUE THREAD

**Issue by rezacsedu** [greenelab/pancancer#105]
Can I combine gene expression, mutation, and copy number data for cancer types prediction?

**Comment by gwaybio** [comment]
nothing stopping you! Although cancer-type (i.e. tissue type) is an easy signal to find

**Comment by rezacsedu** [comment]
Thanks a million for the quick reply. Sorry, but I've one more stupid question, RE: issue#102 (https://github.com/greenelab/pancancer/issues/102): 

Can the same labels (i.e., ttps://github.com/greenelab/pancancer/blob/master/data/sample_freeze.tsv ) be used (let's say) to create a shared representation of the features (out of 3 datasets) to train a multimodal network?

**Comment by gwaybio** [comment]
Yep! So the idea is that you'd train a model to detect _something_ (say cancer-type) but the real endpoint you care about is how the multimodal network combines features together? (and then interpret the combinations?)

**Comment by rezacsedu** [comment]
>>> you care about is how the multimodal network combines features together? 
Yes, exactly.

**Comment by gwaybio** [comment]
Although with such a strong signal like cancer type, I worry that the models will be lazy and won't try to integrate too much
