### ISSUE TITLE
Sample distribution per cancer types? 

### ISSUE THREAD

**Issue by AwesomeDeepAI** [greenelab/pancancer#106]
Dear concern,

Could you please provide the statistics of the different types of data (i.e., for DNA methylation, copy numbers, mutations, miRNA, and gene expression) per cancer types? 

I got the same from an old publication (Link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3919969/pdf/nihms-549280.pdf, see page 14). However, it's pretty old and seems a lot of samples across other cancer types have subsequently been added. 

Thanks in advance.

**Comment by gwaybio** [comment]
Hi BioXAI, thanks for you interest in this project! The specific repo stores analysis code for one [publication](https://doi.org/10.1016/j.celrep.2018.03.046) under the TCGA PanCanAtlas umbrella. I do not have all those statistics on other datatypes easily available. This [resource](https://gdc.cancer.gov/about-data/publications/pancanatlas) might point you in the right direction.

**Comment by AwesomeDeepAI** [comment]
@gwaygenomics, thanks a million for the pointers.
