### ISSUE TITLE
Outsource machine learning to the cognoml package

### ISSUE THREAD

**Issue by dhimmel** [greenelab/pancancer#4]
[Cognoml](https://github.com/cognoma/machine-learning) will need a little time to mature before this is possible. The benefit is two-fold:
- cognoml will be forced to be modular and versatile enough to support this application
- this codebase can be substantially simplified. Currently, it's grown a tad bit unwieldy

@gwaygenomics, would love to know what stands in the way of migrating to a cognoml backend. Then that will help us plan our cognoml dev.

**Comment by gwaygenomics** [comment]
Right now the biggest hurdle are the data sets - data release embargos and publication deadlines are outweighing the convenience of cognoml integration. 

Besides that, I need all input and output parameters to be able to be easily specified.

**Comment by dhimmel** [comment]
> Right now the biggest hurdle are the data sets - data release embargos and publication deadlines are outweighing the convenience of cognoml integration.

Okay will work on making `cognoml` modular so you can specify your own datasets.

> I need all input and output parameters to be able to be easily specified.

What parameters are you talking about?

**Comment by gwaygenomics** [comment]
> What parameters are you talking about?

all hyperparameters, options to drop gene input, options to integrate copy number data, gene inputs, disease-type inputs
