### ISSUE TITLE
When will be data availability

### ISSUE THREAD

**Issue by bluesea2017** [greenelab/pancancer#74]
Hello:
We are very interest with the pancancer,but we can not get the data.

When will be data availability

We look forward to the data pubilic

Thank you

**Comment by gwaygenomics** [comment]
Hi @bluesea2017 

The TCGA PanCanAtlas data is already publicly available and can be downloaded from [UCSC Xena here](https://xenabrowser.net/datapages/?hub=https://pancanatlas.xenahubs.net:443).

We are currently working on adding the data to this repository as well.

**Comment by bluesea2017** [comment]
Hi @gwaygenomics 
  These datas that we can not still download:
pancan_mutation_freeze.tsv
mutation_burden_freeze.tsv
sample_freeze.tsv
How can we download ?

**Comment by gwaygenomics** [comment]
Hi @bluesea2017 

We've updated the repository in #75 to include all data that were used in our publications. `pancancer_classifier.py` can now be used. Note, however, that many additional scripts may not work since we compressed the files to store with git lfs. We are continuing to work to update them

Thanks!
Greg

**Comment by juechenyang** [comment]
Hi @gwaygenomics 

I am still confused about how to get this data:

mutation_burden_freeze.tsv 

Could you help me solve this problem? Thank you

**Comment by gwaygenomics** [comment]
Thanks for your interest in the project @juechenyang 

These data can be accessed after running [`initialize.sh`](https://github.com/greenelab/pancancer/blob/master/initialize.sh). Specifically, it is generated in [`scripts/initialize/process_sample_freeze.py`](https://github.com/greenelab/pancancer/blob/04315434ac6f9f30dce03c8fb9b5757304192f7d/scripts/initialize/process_sample_freeze.py).

I think I could make this easier however - see #80

**Comment by juechenyang** [comment]
@gwaygenomics Thanks so much for your help!
