### ISSUE TITLE
Getting access to the project and data

### ISSUE THREAD

**Issue by asmagen** [greenelab/pancancer#78]
Hello,

Can you provide an explanation to how can I get the access to the data please?

Thanks,
Assaf

**Comment by asmagen** [comment]
Also, the CNV and mutation data I see in the data folder here is supposed to be open access as far as I know. Why is it considered as restricted access here?

**Comment by cgreene** [comment]
It appears you may not have set up your git ssh keypairs correctly:

https://help.github.com/articles/which-remote-url-should-i-use/

**Comment by asmagen** [comment]
It does work after setting up the keys. Thanks

I was wondering where did you get the GISTIC 2 discrete CNV calls? Was it downloaded separately for each cancer type from cBioPortal or was it performed using the pancancer CNV data found [here](https://gdc.cancer.gov/about-data/publications/pancanatlas) and then you ran GISTIC?

Thanks

**Comment by gwaygenomics** [comment]
The CNV calls were generated using GISTIC, but by TCGA data coordinators at [synapse](https://www.synapse.org/#!Synapse:syn5049520.1). (`6d983890c5693a556621142eead3d3bb` md5sum)
