### ISSUE TITLE
can't not find ras_genes.csv in data folder

### ISSUE THREAD

**Issue by 04linsi** [greenelab/pancancer#95]
the ras_genes.csv was needed in  scripts/alternative_genes_pathwaymapper.ipynb file, as follows:
```
# Load Ras Pathway Genes
ras_genes_file = os.path.join('..', 'data', 'ras_genes.csv')
ras_genes_df = pd.read_table(ras_genes_file)
```

I can not find this file in the data folder unfortunately, how can I get this file or generate it by myself?

thanks.

**Comment by cgreene** [comment]
Thanks for the note! Penn is on break until early January, but we'll dig into this and get back to you as soon as possible.

**Comment by gwaybio** [comment]
thanks for the note @04linsi - I added the file in #96. Should be good to go!
