### ISSUE TITLE
cloning into pancancer... permission denied

### ISSUE THREAD

**Issue by Lucianabarros** [greenelab/pancancer#99]
Hello,

I'm trying to clone this "git clone git@github.com:greenelab/pancancer.git", but it keeps giving me the message below. Could you help me? 

Cloning into 'pancancer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Luciana

**Comment by cgreene** [comment]
I'm guessing that since you closed this, you figured it out, but you probably want to clone via https or fork & then clone your fork via the git URL
